language: node_js
node_js:
- '7.2'
before_script:
- npm install
- npm install -g gulp
script:
- gulp package-app
deploy:
  provider: heroku
  app: rocky-peak-51245
  api_key:
    secure: 0DDuDNM3ub9d+LSZ5quvF6dPszUniXbM6Y08KGq3tASSIER47gtQXJvep4fcKlcUZGHijRY3nSuFqQQQPXbwh3AjAbBthUDsUGq/nddozaxdx7rECBCQAB5DwwNr7l8T+DWaZBZ5h66aC9Py1lwVibmKwbohdfOYZAnjZjQQdRzmhSbya6DxdlUk/OStdBas8Udr4pexkPj0H0cIhHiL3ArTxOGseOZ1jdIvrF+k3AX6yakCLP58OHqAMLgWnCifuLYqoouhpVVXlQn2TXXe4R0tpDTYqKhhENVvklnCcET/9JLqCrRvPEVYtShDs9eHjf0Nj78yTCDoUbKTJey+1xgr4IrqQh5wCqxFvK24SK9V3goDKTsThilw9tANcP7s9Xg8glEUp/20yJYKpb1nFAQK893nD09jkSPuZlkNADXf7pvvcNHFQcEMKllNWgckrXOQqNAwYR6QjPtJIapEmbVN+hzEO02ybVnK0tyXjUxGu9V7ZlOruEHZNAIlA/dfgVhNDSsHzhcfwDbhdqKGV5L7urJIXQ7Asmz0SmN7RiKatFQnlH1glJbKScvg1DiRYxBUm5EckkiiAeEFuRIpq3xh0EzoVfcepC+BSspKDWhkIm10UiyAZjrsXn3ebdgOoV9v+OrOYhnxRtY/ql4+b4lYfO5ablwt0Po8NQeVxuw=
  on:
    repo: neburiam/dromedary
